DROP TABLE IF EXISTS FUNCTION_TIME;
DROP TABLE IF EXISTS SQLE_FUNCTION;

CREATE TABLE SQLE_FUNCTION (
    id INT AUTO_INCREMENT PRIMARY KEY ,
    FUNCTION_NAME VARCHAR (100) NOT NULL,
    CATEGORY VARCHAR (250) NOT NULL,
);

-- INSERT INTO SQLE_FUNCTION VALUES (1, 'LINEAR', 'LINEAR');
-- INSERT INTO SQLE_FUNCTION VALUES (2, 'MAX', 'LINEAR');
-- INSERT INTO SQLE_FUNCTION VALUES (3, 'MIN', 'LINEAR');
-- INSERT INTO SQLE_FUNCTION VALUES (4, 'LEAST SQUARE', 'QUADRATIC');
-- INSERT INTO SQLE_FUNCTION VALUES (5, 'SVD', 'LINEAR');

CREATE TABLE FUNCTION_TIME (
    id INT AUTO_INCREMENT PRIMARY KEY,
    TIME_TAKEN_MS INT,
    QUERY VARCHAR(1000),
    CLOUD VARCHAR (50),
    errorCode INT,
    errorMessage VARCHAR (500),
    FUNCTION_NAME varchar (100),

);

-- INSERT INTO FUNCTION_TIME(TIME_TAKEN_MS,CLOUD, FUNCTION_ID) VALUES (100, 'AZURE', 1);
-- INSERT INTO FUNCTION_TIME(TIME_TAKEN_MS,CLOUD, FUNCTION_ID) VALUES  (150, 'AWS', 1);
-- INSERT INTO FUNCTION_TIME(TIME_TAKEN_MS,CLOUD, FUNCTION_ID) VALUES  (250, 'AZURE', 2);
-- INSERT INTO FUNCTION_TIME(TIME_TAKEN_MS,CLOUD, FUNCTION_ID) VALUES  (310, 'AWS', 2);
-- INSERT INTO FUNCTION_TIME(TIME_TAKEN_MS,CLOUD, FUNCTION_ID) VALUES  (420, 'AZURE', 3);
-- INSERT INTO FUNCTION_TIME(TIME_TAKEN_MS,CLOUD, FUNCTION_ID) VALUES  (340, 'AWS', 3);
-- INSERT INTO FUNCTION_TIME(TIME_TAKEN_MS,CLOUD, FUNCTION_ID) VALUES  (240, 'AZURE', 4);
-- INSERT INTO FUNCTION_TIME(TIME_TAKEN_MS,CLOUD, FUNCTION_ID) VALUES  (130, 'AWS', 4);
-- INSERT INTO FUNCTION_TIME(TIME_TAKEN_MS,CLOUD, FUNCTION_ID) VALUES  (240, 'AZURE', 5);
-- INSERT INTO FUNCTION_TIME(TIME_TAKEN_MS,CLOUD, FUNCTION_ID) VALUES  (340, 'AWS', 5);
